version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - http.cors.enabled=true
      - "http.cors.allow-origin=*"
      - http.cors.allow-headers=Content-Type, X-Requested-With
      - http.cors.allow-methods=GET, POST, PUT, DELETE
    ports:
      - 9200:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
