# config/elasticsearch.yml

# Habilitar CORS
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "Content-Type, X-Requested-With"
http.cors.allow-methods: "GET, POST, PUT, DELETE"

# Configuración básica de Elasticsearch
cluster.name: "docker-cluster"
node.name: "node-1"
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
network.host: 0.0.0.0
http.port: 9200

# Deshabilitar seguridad por simplicidad durante el desarrollo (no recomendado en producción)
xpack.security.enabled: false
